- Dockerfile
Hardly take any space and super useful (see #126)
> Add procps and nano back by default in the system distro.

- WSLDVCPlugin/WSLDVCCallback.cpp
Get() is a public method of Comptr class.
> WSLDVCPlugin: Fix debug build typo.

- Dockerfile
- rdpapplist/meson.build
- rdpapplist/rdpapplist_common.c
- rdpapplist/rdpapplist_common.h
- rdpapplist/rdpapplist_protocol.h
- rdpapplist/rdpapplist_server.h
- rdpapplist/server/meson.build
- rdpapplist/server/rdpapplist_main.c
- rdpapplist/server/rdpapplist_main.h
This PR adds rdpapplist which originally temporary placed at FreeRDP project. 
rdpapplist is the WSLg specific module, and it sends the application list from WSLg to Windows client for Start Menu.
This PR is focusing on building new so at WSLg tree, and there is a plan for more code sharing with its client side code at WSLDVCPlugin.
> move rdpapplist to WSLg project from FreeRDP

- Dockerfile
Small request from Steve to have the Dockerfile set the BUILDTYPE to debug when SYSTEMDISTRO_DEBUG_BUILD is specified. This was the best solution I found using parameter expansion of Bash to set the BUILDTYPE to debug when SYSTEMDISTRO_DEBUG_BUILD is non-null and set it to release when it is null. It also changes the comparison to == which Steve pointed out as a bug in the file.
> update docker file to pick debug when debug build_arg is present

- Dockerfile
This fix addresses the debug tools not being installed correctly when SYSTEMDISTRO_DEBUG_BUILD=true is specified. It redeclares the ARG since it's a new image than when it was previously declared and then does an "=" comparison. Docker uses /bin/sh (https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) which I believe is bash specific and not part of sh.
> Fix Dockerfile error to auto install debug tools

- README.md
The previous link now points to a 404; this one should work for a while at the very least.
Ideally there would be a "latest" link (microsoft-edge-dev_latest_amd64.deb), which could point to the newest file in the microsoft-edge-dev folder, reducing the need to use links to specific versions and thus making the command not break so quickly.
> Update Edge DEB link

- Microsoft.WSLg.nuspec
- Microsoft.WSLg.targets
- azure-pipelines.yml
This change adds raw .img file creation to the build pipeline. This is needed because we are investigating switching to a readonly vPMEM device mounted with direct access to improve memory footprint of WSLg.
For testing I have run the pipeline internally on this branch and validated that it passes.
> Produce a .img file in addition to a .vhd for the system distro.

- debuginfo/weston.list
add weston_rdprail_shell to debuginfo list, which is added by https://github.com/microsoft/weston-mirror/pull/35.
> add weston_rdprail_shell to debuginfo list

- WSLGd/main.cpp
fix reading .wslgconfig from user profile path. 
wslpath appends '\n' at end, so it has to be trimmed before appending .wslgconfig file name.
> fix reading .wslgconfig from user profile path

- WSLGd/main.cpp
This issue works around an issue we're currently debugging where msrdc.exe is present but WSLGd does not have execute access.
> Change WSLGd to use access instead of stat to check for execute permissions.

- CONTRIBUTING.md
I fixed a type where CONTRIBUTING.md said "our docker build script expect to" as opposed to "our docker build script expects to".
> Fix Typo in Contributing

- Dockerfile
- Microsoft.WSLg.nuspec
- Microsoft.WSLg.targets
- azure-pipelines.yml
This allows build pipeline to preserve debug symbols within released nuget package.
note: WSLg utilize nuget package as archive format to hand off build artifacts between build pipelines, in this case between WSLg and wsl-build, the outcome nuget is not really expected to be installed directly from itself, thus including symbols in nuget package does not mean symbols are included in final WSL package (or installed). But since the WSLg feed preserves all released nuget, this allows us to locate corresponding symbols even after build artifacts are removed from build pipeline.
> Add system distro debuginfo and RDP plugin PDB to nuget package

- WSLGd/main.cpp
Use dedicated RDP plugin registration for lifted WSL to avoid interference between inbox WSL and lifted WSL.
> Use dedicated RDP plugin registration for lifted WSL

- WSLGd/main.cpp
use doube-quote to wrap wslpath parameter. This is to address the issue reported at https://github.com/microsoft/wslg/issues/689, using double-quote (") is safe as it is not valid character as Windows file path while single-quote (') is valid.
> use doube-quote to wrap wslpath parameter

- README.md
Since [WSL Preview is now available from Windows Store and includes WSLG by default](https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/), this is a much more convenient path for obtaining WSLG than asking customers to switch to the Insiders Program (it's a much smaller ask).
I would also encourage you to change the wording in the Releases page to include this - novices who don't bother to read the README all the way through will tend to think that WSLG is something they can just install with the MSI on Windows 11 from the Releases page, which is not the case.
> Tell customers to grab WSLG from Windows Store

- WSLGd/main.cpp
fix build warnings in WSLGd.
- remove unused c_launchPulse.
- add const for char * as incoming parameter can be string literal.
> fix build warnings in WSLGd

- Dockerfile
To ensure the system clock does not drift from the host, WSL is planning on using chronyd with /dev/ptp0 as a clock source.
> Add chrony to system distro to sync guest clock with the host via /dev/ptp0

- CONTRIBUTING.md
- Dockerfile
- azure-pipelines.yml
build DirectX-headers from specific version source. This is because, by default, mesa is building from 'head'. https://gitlab.freedesktop.org/mesa/mesa/-/blob/21.0/subprojects/DirectX-Headers.wrap#L5
> build DirectX-headers from specific version source

- WSLGd/main.cpp
don't override certain env if already set, some of env could be configured from WSL service or WSLENV.
> WSLGd: don't override certain env if already set

- config/wsl.conf
This change modifies the default user of the system distro to the wslg user. This means that when running `wsl.exe --system` the wslg user will be used instead of root. You can still run as the root user by using `wsl.exe --system -u root`
> Update /etc/wsl.conf to set the default user to wslg

- Dockerfile
enable librsvg2 for SVG format icon.
> enable librsvg2 for SVG format icon

- WSLGd/main.cpp
This change updates WSLG to launch msrdc.exe via the app execution alias. This ensures that the msrdc binary inherits all the package attributes from the WSL package.
> Update WSLGd to use the msrdc execution alias

- WSLDVCPlugin/WSLDVCCallback.cpp
This change updates the plugin to use the wslg.exe that is part of the WSL package instead of the wslg.exe located in system32. I have also added a `#define WSLG_INBOX` that can be used to opt-in to the old behavior.
> Update WSLDVCPlugin to create shortcuts to packaged wslg.exe

- Dockerfile
- WSLGd/FontMonitor.cpp
- WSLGd/FontMonitor.h
- WSLGd/main.cpp
- WSLGd/meson.build
- WSLGd/precomp.h
- config/local.conf
This monitors installation of X11 server fonts at user-distro, and automatically update font path for X server running at  system-distro. This addresses the request at https://github.com/microsoft/wslg/issues/310.
> enable xfonts installed at user distro

- Microsoft.WSLg.nuspec
- Microsoft.WSLg.targets
- WSLGd/main.cpp
- package/wslg_desktop.rdp
allow alternate rdp file via .wslgconfig for experimental desktop remoting mode.
> WSLGd: allow alternate rdp file via .wslgconfig

- WSLGd/precomp.h
This fixes the following error with gcc:
```
main.cpp: In function 'std::string TranslateWindowsPath(const char*)': main.cpp:80:27: error: aggregate 'std::array<char, 128> buffer' has incomplete type and cannot be defined
80 |     std::array<char, 128> buffer;
|                           ^~~~~~
```
std::array was added in 321cf1bcd4fd99112a0cde933816b0d9a4121e6b commit
> WSLg: Include missing array header

- Dockerfile
fix build error (below) at mesa after mariner update.
```
[56/1041] Generating src/compiler/nir/nir_opt_algebraic.c with a custom command (wrapped by meson to capture output)
FAILED: src/compiler/nir/nir_opt_algebraic.c
/usr/bin/meson --internal exe --capture src/compiler/nir/nir_opt_algebraic.c -- /usr/bin/python3 ../src/compiler/nir/nir_opt_algebraic.py
--- stderr ---
Traceback (most recent call last):
File "/work/vendor/mesa/build/../src/compiler/nir/nir_opt_algebraic.py", line 30, in <module>
import nir_algebraic
File "/work/vendor/mesa/src/compiler/nir/nir_algebraic.py", line 32, in <module>
import mako.template
File "/usr/lib/python3.9/site-packages/mako/template.py", line 20, in <module>
from mako import codegen
File "/usr/lib/python3.9/site-packages/mako/codegen.py", line 16, in …
```
> system-distro: fix build error at mesa after mariner update

- WSLGd/FontMonitor.cpp
- WSLGd/common.h
- WSLGd/main.cpp
This update contains
- Allow to load X cursor from user distro.
- Make USE_VSOCK env visible to only weston.
- Windows style path for msrdc arguments.
- Tweak wait time workaround for xset.
- Add check for "../" for rdp file path.
- Use std::filesystem::path for RDP client path.
> WSLGd: misc updates (allow to load X cursor from user distro and etc.)

- CONTRIBUTING.md
Corrected the build instructions to download the lastest from mesa
Please add the label **hacktoberfest-accepted** if you accept this PR
> Since mesa version 21 was merged, the main branch should be checked out instead

- WSLGd/main.cpp
XWayland uses many file descriptors. Bump the soft limit to the max to avoid hitting it. Fixes #862
Similar to https://github.com/swaywm/sway/pull/6629 and https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2235
> WSLGd: Raise the NOFILE limit

- Dockerfile
- WSLGd/main.cpp
This redirects the logging from FreeRDP to a file at /mnt/wslg/wlog.log, also enable FreeRDP debugging when building system-distro with debug option enabled.
> WSLGd: redirect FreeRDP log to a file

- Dockerfile
update to official mariner 2.0 release. https://microsoft.github.io/CBL-Mariner/announcing-mariner-2.0/
> wslg: update mariner to 2.0 official release

- WSLGd/ProcessMonitor.cpp
fix to add private env when relaunching child process at process monitor.
> WSLGd: fix relaunch weston with env

- WSLGd/ProcessMonitor.cpp
- WSLGd/main.cpp
This change to launch Windows RDP client executable with 'init' explicitly to avoid conflict in binfmt, which is reported at https://github.com/microsoft/WSL/issues/9257#issuecomment-1345550170.
> WSLGd: launch RDP client with 'init' explicitly

- WSLGd/ProcessMonitor.cpp
- WSLGd/main.cpp
This allows WSLGd, weston, FreeRDP and pulseaudio to send log to custom path including /dev/kmsg, for diagnostic purposes.
> WSLGd: allow customize log file path

- Dockerfile
This change adds libacl to the runtime dependencies of the system distro vhd. We are planning on using this functionality in an upcoming WSL feature.
> Add libacl to runtime dependencies

- Dockerfile
Turns out we don't need this.
Reverts microsoft/wslg#984
> Revert "Add libacl to runtime dependencies"

- WSLGd/main.cpp
This PR updates pulseaudio launch options to do followings. 
- Do not allow exit.
- Do not exit after long idle.
- Create new log file after restarting.
- Add time prefix in log file.
> WSLGd: update pulseaudio launch options

- Dockerfile
This PR enable SVG format icon can be used by WSLg to address issue reported at https://github.com/microsoft/wslg/issues/70. This PR requires https://github.com/microsoft/weston-mirror/pull/145 to be completed first.
> WSLg: support SVG format icon

- Dockerfile
Update CBL-Mariner base image to [2.0.20230630](https://github.com/microsoft/CBL-Mariner/releases/tag/2.0.20230630-2.0).
> WSLg: Update CBL-Mariner base image to 2.0.20230630

- config/BUILD.md
The step about copying the DirectX headers was missing from this howto.
Used the step in the Azure pipeline file as the source and to avoid renumbering everything, I added the step to the existing `mesa` step.
Signed-off-by: Nuno do Carmo nuno.carmo@suse.com
> Added DirectX headers step

- Microsoft.WSLg.nuspec
- Microsoft.WSLg.targets
- azure-pipelines.yml
This change removes the logic to build and package .img disk images since WSL doesn't use them and it makes the nuget package twice as big
> Remove logic to build and package .img disk images

- azure-pipelines.yml
This PR removes the unused variable group "Keys" from azure-pipelines.yml.
> WSLg build: remove unused variable group "Keys"

- Dockerfile
This PR updates Mariner core image to 20231130 release, this also includes to add build date in versions.txt.
> WSLg: update Mariner to 20231130 release

- WSLGd/main.cpp
This PR updates the order of arguments given to RDP client software when WSLGd is invoking them. This is to support incoming updates of msrdc release.
> WSLGd: update msrdc parameter order

- Dockerfile
This PR to address https://github.com/microsoft/wslg/issues/1221.
> WSLg: Update Mariner to 2.0.20240112

- .github/ISSUE_TEMPLATE/bug_report.yml
- WSLGd/main.cpp
This change removes the logic to set the core pattern to /mnt/wslg/dumps and updates the issue template to direct users to the new coredump folder
> Update wslgd to use the new wsl coredump infrastructure

- Dockerfile
- azure-pipelines.yml
Upgrade CBL-Mariner to 2.0.20250207
> Upgrade CBL-Mariner to 2.0.20250207

- .github/ISSUE_TEMPLATE/bug_report.yml
Bug reporting templates are not available because of this issue, so this should resolve the problem.
> Escape backslash in bug report issue template

- WSLDVCPlugin/WSLDVCPlugin.vcxproj
This PR to fulfill the requirement of Rule BA2004 and BA2024 by upgrading the toolset to v143 and enabling Spectre Mitigation.
> WSLDVCPlugin: update toolset to v143 and enable SpectreMitigation
