microsoft/wslg

- .github/ISSUE_TEMPLATE/bug_report.md
Made a very small fix to change the issue template from using \\wsl\ (which won't work on newer builds) to \\wsl$\ (which will work on every build).
> Updated bug_report.md

- azure-pipelines.yml
* Rename WSLDVCPLugin artifact name
* Increase timeout
> Minor fixes to ADO pipeline

- WSLGd/main.cpp
Redirect stderr to a file for debugging
> redirect stderr to a file for debugging

- Dockerfile
- config/local.conf
Add Windows's fonts directory to fontconfig path.
> allow system-distro to access Windows fonts

- Dockerfile
set buildtype for WSLGd from global define in Dockerfile.
> set buildtype for WSLGd

- WSLGd/main.cpp
- WSLGd/precomp.h
enable core dumps for WSLGd and its children.
> enable core dumps for WSLGd and its children

- CONTRIBUTING.md
- Dockerfile
This updates the CONTRIBUTING.md file to provide instructions on building a debug version of the system distro.
> Update CONTRIBUTING markdown 

- WSLGd/main.cpp
This change introduces support for WSLGd for two new environment variables that are being added to the system distro to plumb the path where WSL is installed, and the path of the user profile.
> WSLGd support for WSL2_INSTALL_PATH and WSL2_USER_PROFILE environment variables

- README.md
**What does this PR do?**
Minor documentation update. The suggestion was that `apt update` updated packages when it's purpose is to update the lists. I've updated this to match the wording from the man page:
```
apt 2.0.4 (amd64)
Usage: apt [options] command
apt is a commandline package manager and provides commands for
searching and managing as well as querying information about packages.
It provides the same functionality as the specialized APT tools,
like apt-get and apt-cache, but enables options more suitable for
interactive use by default.
Most used commands:
list - list packages based on package names
search - search in package descriptions
show - show package details
install - install packages
reinstall - reinstall packages
remove - remove packages
autoremove - Remove …
```
> nit: updating apt update to reflect expected behaviour

- azure-pipelines.yml
Missed downloading the .img files prior to packaging the nuget package.
> Add missing download .img artifacts step

- WSLGd/main.cpp
launch msrdc.exe instead of mstsc.exe if it's installed at WSL install path.
> add msrdc.exe path

- WSLGd/main.cpp
Explicitly specify socket by parameter for weston.
> specify socket by parameter for weston

- Dockerfile
This changes removes the python3-libs and deletes some documentation from the system distro to reduce the vhd size.
> Remove packages to reduce the vhd size

- Dockerfile
update mariner base image to 1.0.20220226
> update mariner base image to 1.0.20220226

- WSLGd/main.cpp
add option to use mstsc.exe as RDP client
> add option to use mstsc.exe as RDP client

- Dockerfile
update Dockerfile to change dependencies build order.
> update Dockerfile to change dependencies build order

- samples/container/Dockerfile.glxgears
- samples/container/Dockerfile.glxinfo
- samples/container/Dockerfile.xclock
remove Dockerfile to avoid Secure Supply Chain Analysis errors
> remove Dockerfile to avoid Secure Supply Chain Analysis errors

- azure-pipelines.yml
> fix DirectX-headers for arm64

- WSLDVCPlugin/WSLDVCCallback.cpp
- WSLGd/main.cpp
This PR contains
- allow private RDP plugin for testing.
- make sure directory is still exist when app installation notification is delivered, this address https://github.com/microsoft/wslg/issues/750.
> allow private RDP plugin for testing and make sure directory presense

- WSLDVCPlugin/WSLDVCCallback.cpp
- WSLDVCPlugin/WSLDVCFileDB.cpp
- WSLDVCPlugin/dllmain.cpp
- WSLDVCPlugin/utils.cpp
- WSLDVCPlugin/utils.h
obtain icon file from lnk file for RemoveAppProvider API.
> obtain icon file from lnk file for RemoveAppProvider API

- WSLGd/main.cpp
simplify weston command line construction and validate gdbserver port is numeric.
> simplify weston command line construction

- Dockerfile
> Revert "enable librsvg2 for SVG format icon"

- debuginfo/weston.list
replace systemd-notify with wslg-notify for strip/archive debuginfo.
> debuginfo: replace systemd-notify with wslg-notify

- WSLGd/common.h
- WSLGd/main.cpp
- WSLGd/precomp.h
> WSLGd: add timestamp to log

- WSLGd/FontMonitor.cpp
- WSLGd/FontMonitor.h
- WSLGd/ProcessMonitor.cpp
independently monitor child process for font monitor, this allow to retrieve exit status from child process involved at font monitor.
> WSLGd: independently monitor child process for font monitor

- Dockerfile
WSLg: update Mariner to 2.0.20230107.
> WSLg: update Mariner to 2.0.20230107

- samples/container/Containers.md
- samples/container/build.sh
- samples/container/run.sh
This PR adds a sample showing how to access VA-API video acceleration via vGPU with containers.
> samples/container: Add vGPU video acceleration docker sample

- Dockerfile
update pulseaudio build options for v16.1 for https://github.com/microsoft/pulseaudio-mirror/pull/2
> WSLg: update build options for pulseaudio v16.1

- WSLGd/FontMonitor.cpp
Add support for alternative font path in distributions which use the `/usr/share/X11/fonts` directory.
Changes:
1. Defined the `ALT_FONT_PATH` and `ALT_DISTRO_FONT_PATH` macros 
2. Updated the `Start()` method to check for the existence of both font paths
3.  Updated the `Stop()` method to remove both the default and alternative font paths from the monitor if they were added
> WSLGd: support alternative font path

- Dockerfile
- azure-pipelines.yml
This PR updates system distro's mesa to v23.1.0 and DirectX-Headers to v1.608.0.
> WSLg: update system distro's mesa to v23.1.0

- WSLGd/ProcessMonitor.cpp
- WSLGd/precomp.h
This is revised of https://github.com/microsoft/wslg/pull/831.
> WSLGd: stop restarting processes if they exit more than 10 times in a minute

- azure-pipelines.yml
This change adds pipeline logic to publish symbols for  WSLDVCPlugin.dll to our symbol server.
> Add logic to publish symbols WSLDVCPlugin.dll

- CONTRIBUTING.md
- config/BUILD.md
This PR reflects the documentation update by https://github.com/microsoft/wslg/pull/1077.
> document: update system distro build instruction for mesa update

- WSLDVCPlugin/WSLDVCCallback.cpp
According to RDP client software (mstsc/msrdc), plugin's OnDataReceived() and OnClose() can be called from different thread simultaneously due to usage of threadpool. This PR adds a critical section to serialize the processing of those callbacks, and stop processing data at OnDataReceived() as soon as OnClose() is called.
> WSLDVCPlugin: fix RDP plugin callback thread for possible race condition

- WSLDVCPlugin/WSLDVCCallback.cpp
This change updates the msrdc plugin to use the new path of the wslg executable instead of a hard-coded path to the app execution alias.
> Update the path of wslg.exe for the new MSI package.

- Dockerfile
This change updates the Mariner image to the recently released November 2023 release.
> Update Mariner image to 2.0.20231106

- WSLGd/main.cpp
This change updates the port number of the vsock used for connecting MSRDC to Weston to be in the reserved range.
> Change vsock for weston RDP channel to be in the reserved range

- WSLGd/main.cpp
Working on a change to fix WSLg on Ubuntu 24.04. I think this will be part of the solution.
> Change XDG runtime dir mode to 0777

- Dockerfile
Update Mariner 2.0.20240609 (tag 2.0.20240615)
> WSLg: Update Mariner to 2.0.20240609

- Dockerfile
Update CBL-Mariner to 2.0.20240829
> WSLg: Update CBL-Mariner to 2.0.20240829

- WSLGd/main.cpp
This change is a follow up to this WSL PR which exposes a command-line utility to query the VM ID.
https://github.com/microsoft/WSL/pull/13212
> Switch WSLg to use new wslinfo --vm-id functonality

- Dockerfile
- azure-pipelines.yml
This PR contains.
- Address cross platform build issues with azure pipeline.
- Update Azure Linux 2.0 to 20250701.
- Tweak build options for FreeRDP.
> Address cross platform build issues and misc updates

- WSLDVCPlugin/WSLDVCPlugin.vcxproj
This PR enables code flow guard on RDP Plugin to meet Rule BA2008 requirement.
> WSLDVCPlugin: enable code flow guard on RDP Plugin

- WSLGd/main.cpp
- This PR restricts what weston shell can be used, it's only rdprail-shell or desktop-shell. Also selects proper rdp file based on the selected shell type.
> WSLGd: don't allow arbitrary settings for shell
